name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['v*']
    paths: ['src/**', '.github/workflows/**']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/generator
jobs:
  push_to_registry:
    environment:
      name: staging_feeds
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to GitHub package feed
        uses: docker/login-action@v1.14.1 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
      - run: |
          $version = $Env:BRANCH_NAME -replace "refs/tags/v",""
          echo "::set-output name=version::${version}"
        shell: pwsh
        id: getversion
        if: contains(github.ref, 'refs/tags/v')
        env:
          BRANCH_NAME: ${{ github.ref }}
      - name: Push to GitHub Packages - Nightly
        if: contains(github.ref, 'refs/head/main')
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nightly
      - name: Push to GitHub Packages - Release
        if: contains(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.getversion.outputs.version }}
